In [2]:
import numpy as np
import pandas as pd
import openpyxl as op

## series

In [67]:
labels = ['a','b','c']
my_list = [10,20, 30]
arr = np.array([10,20, 30])
dic = {1:10, 2:20, 3:30}

In [68]:
pd.Series(my_list)
pd.Series(my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [69]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [70]:
pd.Series(dic)

1    10
2    20
3    30
dtype: int64

## dataframes

In [3]:
data = {
    "Name": ['John', 'Anna', 'Peter', 'Linda'],
    "Age": [28, 34, 29, 42],
    "City": ['New York', 'Paris', 'Berlin', 'London'],
    "Salary": [65000, 70000, 62000, 85000]
}
pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
data_list = [
   ['John', 28, "New York", 65000],
   ['Anna', 34, "Paris", 70000],
   ['Peter', 29, "Berlin", 62000],
   ['Linda', 42, "London", 85000]
]
pd.DataFrame(data_list)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000